# Generated by Django 5.0.3 on 2024-03-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='picture',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
