# Generated by Django 5.0.3 on 2024-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_image_customuser_picture_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
