# Generated by Django 5.1 on 2024-08-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aboutus", models.TextField()),
                ("supportNumber", models.CharField(max_length=16)),
                ("telegram", models.CharField(max_length=128)),
                ("whatsapp", models.CharField(max_length=128)),
                ("address", models.TextField()),
                ("phoneNumber", models.CharField()),
                ("mobileNumber", models.CharField(max_length=16)),
            ],
        ),
    ]
