# Generated by Django 5.1 on 2024-08-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="mobileNumber",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="phoneNumber",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="supportNumber",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="telegram",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="whatsapp",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
