# Generated by Django 5.1 on 2024-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_store_address_alter_store_mobilenumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="aboutus",
            field=models.TextField(null=True),
        ),
    ]
