# Generated by Django 5.1 on 2024-08-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_store_aboutus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="aboutus",
            new_name="aboutUs",
        ),
    ]
