# Generated by Django 5.1 on 2024-08-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_rename_aboutus_store_aboutus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="aboutUs",
            new_name="aboutus",
        ),
    ]
