# Generated by Django 5.1 on 2024-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_aboutus_store_aboutus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="mobileNumber",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="supportNumber",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
