# Generated by Django 5.1 on 2024-08-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_store_mobilenumber_alter_store_supportnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="aboutus",
            field=models.TextField(blank=True, null=True),
        ),
    ]
