[tool.pylint.format]
max-line-length = 100

[tool.pylint.messages_control]
disable = ["missing-module-docstring", "missing-function-docstring","missing-class-docstring","too-many-ancestors","no-member","too-few-public-methods"]

[tool.black]
line-length = 100

[tool.pylint.main]
init-hook ="""
try:
  import pylint_venv
except ImportError:
  pass
else:
  pylint_venv.inithook()
"""

[tool.mypy]
python_executable="~/.local/share/virtualenvs/chemical-shop-drf-backend-bQisqIcK/bin/python"
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "config.settings"
