# Generated by Django 5.0.3 on 2024-04-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('I', 'IN_PROGRESS'), ('R', 'READY'), ('D', 'DELIVERED')], default='I', max_length=1, null=True),
        ),
    ]
