# Generated by Django 5.0.3 on 2024-04-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
