# Generated by Django 5.0.3 on 2024-03-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='english_name',
            field=models.CharField(default='English Name', max_length=255),
        ),
    ]
