# Generated by Django 5.0.7 on 2024-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="diameter",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.CharField(max_length=64),
        ),
    ]
